direction: right
pg2: rectangle
pg2.shape: rectangle
pg3: square
pg3.shape: square
pg4: page
pg4.shape: page
pg5: parallelogram
pg5.shape: parallelogram
pg6: document
pg6.shape: document
pg7: cylinder
pg7:shape: cylinder
pg8: queue
pg8.shape: queue
pg9: package
pg9.shape: package
pg10: step
pg10.shape: step
pg11: callout
pg11.shape: callout
pg12: stored_data
pg12.shape: stored_data
pg13: person
pg13.shape: person
pg14: diamond
pg14.shape: diamond
pg15: oval
pg15.shape: oval
pg17: circle
pg17.shape: circle
pg18: hexagon
pg18.shape: hexagon
pg19: cloud
pg19.shape: cloud
pg19: text
pg19.shape: text
pg20: code
pg20.shape: code
pg21: class
pg21.shape: class
pg22: sql_table
pg22.shape: sql_table
pg23: image
pg23.shape: image
pg23.icon: https://icons.terrastruct.com/infra/019-network.svg
pg24: sequence_diagram
pg24.shape: sequence_diagram
